### ISSUE TITLE
Backend create msg & error cases should return json...

### ISSUE THREAD

**Issue by elabonte-at-strat** [JStrategia/fullstack-react-template#26]

**Comment by elabonte-at-strat** [comment]
Il semblerait que le problème venait du fait que je voulais inclure l'objet _err_ reçu dans un catch pour donner un max de détails dans la réponse. En tentant de sérialiser cet objet on obtient une erreur comme celle ci:
```
{
    "errorType": "TypeError",
    "errorMessage": "Converting circular structure to JSON\n    --> starting at object with constructor 'IncomingMessage'\n    |     property 'req' -> object with constructor 'ClientRequest'\n    --- property 'res' closes the circle",
    "stack": [
        "TypeError: Converting circular structure to JSON",
        "    --> starting at object with constructor 'IncomingMessage'",
        "    |     property 'req' -> object with constructor 'ClientRequest'",
        "    --- property 'res' closes the circle",
        "    at JSON.stringify (<anonymous>)",
        "    at sendFail (/var/task/index.js:23217:16)",
        "    at Runtime.createMessage [as handler] (/var/task/index.js:23204:12)",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
    ]
}

```
